
GET http://localhost/msa/pay/wallet/getall
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxNiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzcyNjkwMTIyLCJleHAiOjE3NzI2OTM3MjJ9.8MDm1_MvBtGoGHZjjUv_FZ_0-wYnO_vWNm7KuIDqunIKD5x7RWGXz16uWG6vSto4