
POST http://localhost/msa/res/reserve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxNiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzcyNzcwNzY3LCJleHAiOjE3NzI3NzQzNjd9.kV-dRXbjKwVPDvDI0BTEgTLP5GdQQWGDdGINeD0Smhyzk7qUqOfZkO5ISVA8pgPa

{
  "event_id": 2,
  "ticket_count": 1,
  "member_id": 16
} 