GET http://localhost/msa/core/admin/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI1Iiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NzQwMDIzMDIsImV4cCI6MTc3NDAwNTkwMn0.X8_WBKRHnc6ysHtlvOwiAkHl5PK4pxzklhG-kmIOC6ocW_QOK_t5js3QqftSYlrW
                        