GET http://localhost/msa/pay/wallet/getall
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxNiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzcyNzcwNzY3LCJleHAiOjE3NzI3NzQzNjd9.kV-dRXbjKwVPDvDI0BTEgTLP5GdQQWGDdGINeD0Smhyzk7qUqOfZkO5ISVA8pgPa