
POST http://localhost/msa/res/reserve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxNiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzcyNzg4NjY0LCJleHAiOjE3NzI3OTIyNjR9.P2sjHagCmXDunjyr8nieYB7CtEu6PYqQu7kIIYUF2_h9niuwm6BlKrZ27Hmx3K8j

{
  "event_id": 2,
  "ticket_count": 1,
  "member_id": 16
} 