GET http://localhost/msa/core/admin/settlement/stats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxNiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzczMzk4Mjc2LCJleHAiOjE3NzM0MDE4NzZ9.CdsaptHGOULoC08NXghKzHzG04H7hKEiZXOAPHcQ5Qnue7Xj8dfUb2FsnWSY_aoA
