
GET http://localhost/msa/pay/wallet/getall
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxNiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzcyNjk3MTQ5LCJleHAiOjE3NzI3MDA3NDl9.0cdVQo47l9E3kX-DYafIPUBhk9FSl0wG-7inGNtgbX9VqWb5osQqjtMxLocgm6eR