# [Project Setup]
spring.application.name=core

# [Server Settings]
# ���� ���� (��Ʈ ��)
server.port=8080

# [File Storage Settings] - �߰��� �κ�
file.upload.dir=C:/msa_uploads/

# [Database Settings]
spring.datasource.url=jdbc:postgresql://34.50.7.72:5432/msa_core_db
spring.datasource.username=app_user
spring.datasource.password=user1234

# [MyBatis Settings]
# Mapper XML
mybatis.mapper-locations=classpath:mappers/*.xml
# Model
mybatis.type-aliases-package=com.example.test.dto
# DB
mybatis.configuration.map-underscore-to-camel-case=true

# [Logging Settings]
# SQL 
logging.level.com.example.demo.mapper=debug

# [Security Settings]
spring.security.user.name=admin
spring.security.user.password=1234

# [JPA/Hibernate Settings]
# OSIV(Open Session In View)
spring.jpa.open-in-view=false
# JPA
spring.jpa.hibernate.ddl-auto=update
# SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# sign up
sign.up.url=http://localhost/signup
# ?��??����??�� ??��?��? ?????��??��?????��
login.user.url=http://localhost/?token=

# Kakao Login
kakao.client-id=60436ff86cba6a6503953dcc36304a02
kakao.client-secret=pAqtG3RL0Uj3LIMSr9PALdZRfYYpEKm5
kakao.redirect-uri=http://localhost/msa/core/api/login/kakao/callback

# Naver Login
naver.client.id=xz_SSwG0wjHf_lMwuKwV
naver.client.secret=H0n9yFjPov
naver.redirect.uri=http://localhost/msa/core/api/login/naver/callback

# Google Login
google.client.id=494479452656-uats3l085eua4ltgm9enfd0rv3as9noo.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost/msa/core/api/login/google/callback

# payService
pay.url=http://localhost:8083/wallet/balance?member_id=

# JWT Secret Key
jwt.secret=your-very-very-secret-key-should-be-very-long-and-secure

# Mail
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=gor_ge0us@naver.com
spring.mail.password=37PEPU698UM6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com
spring.mail.properties.mail.smtp.starttls.enable=false

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:msa_mq}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:mq1234}

# WebFlux�� �־ ����ó�� Tomcat(Servlet)�� ����ϵ��� ������
spring.main.web-application-type=servlet