# [Project Setup]
spring.application.name=core

# [Server Settings]
# ê³µíµ ì¤ì  (í¬í¸ ë±)
server.port=8080


# [Database Settings]
# ê°ë°ì© ì¸ë¶ PostgreSQL ìë² ì ì ì ë³´
# ì¤ì  ë°°í¬ ì docker-composeë¡ ë´ë¶ ë¤í¸ìí¬(msa-network)ë¥¼ íµí´ ì°ê²°íëë¡ ì¤ë²ë¼ì´ë©
spring.datasource.url=jdbc:postgresql://34.158.208.117:5432/msa_core_db
spring.datasource.username=app_user
spring.datasource.password=user1234

# [MyBatis Settings]
# Mapper XML íì¼ì ìì¹ (src/main/resources/mappers í´ë ê¸°ì¤)
mybatis.mapper-locations=classpath:mappers/*.xml
# Model í´ëì¤ë¤ì´ ëª¨ì¬ìë í¨í¤ì§ (Alias ì¤ì ì©)
mybatis.type-aliases-package=com.example.test.dto
# DBì snake_case ì»¬ë¼ì Javaì camelCase íëë¡ ë§¤í
mybatis.configuration.map-underscore-to-camel-case=true

# [Logging Settings]
# SQL ë¡ê·¸ ì¶ë ¥ ì¤ì  (ëë²ê¹ì©)
logging.level.com.example.demo.mapper=debug

# [Security Settings]
# ì¤íë§ ìíë¦¬í° ìì ìì´ë
spring.security.user.name=admin
spring.security.user.password=1234

# [JPA/Hibernate Settings]
# OSIV(Open Session In View) ë¹íì±í (ì±ë¥ ë° ì»¤ë¥ì í¨ì¨ì ìí¨)
spring.jpa.open-in-view=false

# JPAê° DB íì´ë¸ì ìëì¼ë¡ ìì±/ìì 
spring.jpa.hibernate.ddl-auto=update

# SQL ë¡ê·¸ ì¶ë ¥ ë° í¬ë§·í
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# sign up
sign.up.url=http://localhost:3000/signup
# ë¡ê·¸ì¸ ì±ê³µ ë¦¬ë¤ì´ëí¸
login.user.url=http://localhost:3000?token=

# Kakao Login
kakao.client-id=60436ff86cba6a6503953dcc36304a02
kakao.client-secret=pAqtG3RL0Uj3LIMSr9PALdZRfYYpEKm5
kakao.redirect-uri=http://localhost/msa/core/api/login/kakao/callback

# Naver Login
naver.client.id=xz_SSwG0wjHf_lMwuKwV
naver.client.secret=H0n9yFjPov
naver.redirect.uri=http://localhost/msa/core/api/login/naver/callback

# Google Login
google.client.id=494479452656-uats3l085eua4ltgm9enfd0rv3as9noo.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost/msa/core/api/login/google/callback

# payService
pay.url=http://localhost:8083/wallet/balance?member_id=

# JWT Secret Key
jwt.secret=your-very-very-secret-key-should-be-very-long-and-secure

# Mail ë³¸ì¸ì¸ì¦Â
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=gor_ge0us@naver.com
spring.mail.password=37PEPU698UM6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com
spring.mail.properties.mail.smtp.starttls.enable=false

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# RabbitMQ ì¤ì 
spring.rabbitmq.host=localhost
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:msa_mq}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:mq1234}

# WebFlux가 있어도 기존처럼 Tomcat(Servlet)을 사용하도록 강제함
spring.main.web-application-type=servlet